name: tea_challenge
description: Challenge app for the company &quot;Tea&quot;.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  clock: ^1.1.2
  collection: ^1.18.0
  date_utils: ^0.2.0
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  get_it: ^8.2.0
  go_router: ^16.2.0
  google_fonts: ^6.3.1
  json_annotation: ^4.9.0
  logging: ^1.2.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner:
  drift_dev: ^2.28.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  fake_async: ^1.3.2
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  mockito: ^5.4.4

flutter:
  uses-material-design: true
